# Generated by Django 5.0 on 2023-12-16 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filesgroup_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesgroup',
            name='files',
            field=models.ManyToManyField(null=True, to='files.file'),
        ),
        migrations.AlterField(
            model_name='filesgroup',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
