# Generated by Django 5.0 on 2023-12-16 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_filesgroup_files_alter_filesgroup_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesgroup',
            name='files',
            field=models.ManyToManyField(to='files.file'),
        ),
        migrations.AlterField(
            model_name='filesgroup',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
