# Generated by Django 5.0 on 2023-12-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_filesgroup_files_file_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesgroup',
            name='name',
            field=models.CharField(default='group', max_length=50),
        ),
    ]
