# Generated by Django 5.0 on 2023-12-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_file_groups_filesgroup_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='editor_id',
            new_name='editor',
        ),
    ]
