# Generated by Django 5.0 on 2023-12-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_filesgroup_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
