# Generated by Django 4.2.7 on 2024-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_remove_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='operation',
        ),
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('Check-in', 'Check-in'), ('Check-out', 'Check-out')], default='Check-in', max_length=10),
        ),
    ]
